#we are creating a workflow yaml file here

name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo code
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"
      
      - name: Install Dependencies
        run: |
          python -m pip install -r requirements.txt
      

      - name: Install pytest-cov report
        run: |
          python -m pip install pytest-cov
      
      - name: Run tests
        run: |
          python -m pytest -v --cov=src tests | tee pytest-coverage.txt

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
            pytest-coverage-path: ./pytest-coverage.txt
            junitxml-path: ./pytest.xml